### DISCUSSION TITLE
Gradio Themes not using max-width of the screen.

### DISCUSSION THREAD

**Discussion by TheSeventhCode** [vladmandic/sdnext#2370] [Q&A]
Hey there,

I've recently updated to the latest version (the one before was something around the end of September) and with it some new gradio updates seem to have come.
What I find a bit weird and would hope to change, is that the entire UI has now a max-width:

![image](https://github.com/vladmandic/automatic/assets/116310652/edb3caca-5f4d-4712-bea7-13adec24ba4f)
(I'm using the `idspicQstitho/dracula_revamped` theme)

I've tried removing that with a custom `user.css`, but my styling just gets overridden by the theme CSS.
CSS styling of the `gradio-contrainer` div element within `gradio-app`:
```css

element.style {
    min-height: initial;
    flex-grow: 1;
}
@media (min-width: 1536px)
.app.svelte-1kyws56.svelte-1kyws56 {
    max-width: 1536px;
}
@media (min-width: 1280px)
.app.svelte-1kyws56.svelte-1kyws56 {
    max-width: 1280px;
}
@media (min-width: 1024px)
.app.svelte-1kyws56.svelte-1kyws56 {
    max-width: 1024px;
}
@media (min-width: 768px)
.app.svelte-1kyws56.svelte-1kyws56 {
    max-width: 768px;
}
@media (min-width: 640px)
.app.svelte-1kyws56.svelte-1kyws56 {
    max-width: 640px;
}
.app.svelte-1kyws56.svelte-1kyws56 {
    position: relative;
    margin: auto;
    padding: var(--size-4);
    width: 100%;
    height: 100%;
}
gradio-app > .gradio-container {
    max-width: 100%;
}
```

As you can see my custom `-max-widht: 100%` is last and gets ignored.

Is there some setting to change this back, or some way to have my CSS take higher priority?

Thanks
